---
title: "R markdown coding challange"
output: 
  md_document:
  word_document:
    toc: true
  html_document:
  pdf_document: 
    toc: true
date: "2025-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# [Find data here](https://doi.org/10.1094/PDIS-06-21-1253-RE)

this is the code from coding challenge 3 question 5
```{r}
library(knitr)
library(rmarkdown)
library(pandoc)
library(tidyverse)
library(ggrepel)
library(ggpubr)
library(tinytex)

mycodata = read.csv("MycotoxinData.csv", na.strings = "na")
View(mycodata)
str(mycodata)
mycodata$Treatment=as.factor(mycodata$Treatment)
mycodata$Cultivar=as.factor(mycodata$Cultivar)
str(mycodata)

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
colorchoice= c("#56B4E9","#009E73")
```

Graphs with DON
```{r}
mycodata$Treatment2= factor(mycodata$Treatment, levels= c("NTC","Fg","Fg + 37","Fg + 40","Fg + 70")) #new column with correct order
graph2= ggplot(mycodata, aes(x=Treatment2, y=DON, fill=Cultivar)) + #uses corrected order
  geom_boxplot(position=position_dodge(0.5),outlier.color = "NA") +
  xlab("") + ylab("DON (ppm)") +
  geom_point(pch=21, alpha=0.6, position=position_jitterdodge(dodge.width=0.9)) +
  scale_fill_manual(values= colorchoice)+
  theme_classic()+
  facet_wrap(~Cultivar)
graph5= graph2 + geom_pwc(aes(group=Treatment2, method= "t_test", label= "p.adj.format"))
```

Graph with X15ADON
```{r}
graph3= ggplot(mycodata, aes(x=Treatment2, y=X15ADON, fill=Cultivar)) +
  geom_boxplot(position=position_dodge(0.5),outlier.color = "NA") +
  xlab("") + ylab("15ADON") +
  geom_point(pch=21, alpha=0.6, position=position_jitterdodge(dodge.width=0.9)) +
  scale_fill_manual(values= colorchoice)+
  theme_classic()+
  facet_wrap(~Cultivar)
graph6= graph3 + geom_pwc(aes(group=Treatment2, method= "t_test", label= "p.adj.format"))
```

```{r}
graph4= ggplot(mycodata, aes(x=Treatment2, y=MassperSeed_mg, fill=Cultivar)) +
  geom_boxplot(position=position_dodge(0.5),outlier.color = "NA") +
  xlab("") + ylab("Seed Mass (mg)") +
  geom_point(pch=21, alpha=0.6, position=position_jitterdodge(dodge.width=0.9)) +
  scale_fill_manual(values= colorchoice)+
  theme_classic()+
  facet_wrap(~Cultivar)
graph7= graph4 + geom_pwc(aes(group=Treatment2, method= "t_test", label= "p.adj.format"))
```

```{r}
ggarrange(graph5,graph6,graph7, ncol=3, nrow=1, common.legend = TRUE)
```

